[[block]]
block = "cpu"
interval = 5

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %d/%m %R') "
interval = 60


[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"


[icons]
icons = "material-nf"

[theme]
theme = "modern"

[theme.overrides]
idle_bg = "#fcf7ef"
idle_fg = "#242521"
warning_bg = "#c5c3b8"
warning_fg = "#242521"
separator = ""
critical_bg = "#9f0d0f"
critical_fg = "#000000"
good_bg = "#e0e0e0"
good_fg = "#000000"
info_bg = "#e0e0e0"
info_fg = "#000000"
